apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-simple-webserver
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  project: default
  source:
    repoURL: https://github.com/anatoad/ci_cd_lab
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
