apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/anatoad/ci_cd_lab:sha256:496bfd77fc26a7b7aa037bcb2587a0e94644b8a804f003c781edb52a71d3016e
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
